<?php
/**
 * @file
 * Module file for my first module.
 */

/**
 * Implements hook_menu().
 *
 * Provides a default page to explain what this module does.
 */
function firstmodule_menu() {
    $items['custom/firstmodule'] = array(
        'page callback' => 'firstmodule_page',
        'access callback' => TRUE,
        'title' => 'First Module',
    );
    return $items;
}

/**
 * Simple page function to explain what the block example is about.
 */
function firstmodule_page() {
    $page = array(
        '#type' => 'markup',
        '#markup' => t('This is the explanation page of my awesome module.'),
    );
    return $page;
}

/**
 * Implements hook_help()
 * @param $path
 * @param $arg
 * @return string
 */
function firstmodule_help($path, $arg) {
    switch ($path) {
        // Main module help for the block module
        case 'admin/help#firstmodule':
            return '<p>' . t('You don\'t need help with this awesome module.') . '</p>';
    }
}

function firstmodule_theme() {
    return array(
        'firstmodule_text_form'  => array(
            'render element' => 'form',
            // In this one the rendering will be done by a template file
            // (theming-example-text-form.tpl.php) instead of being rendered by a
            // function. Note the use of dashes to separate words in place of
            // underscores. The template file's extension is also left out so that
            // it may be determined automatically depending on the template engine
            // the site is using.
            'template' => 'firstmodule-text-form',
        ),
    );
}
